version: '2'

services:
  redis-server:
    image: redis:3.2.10
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    volumes:
      - ~/volumes/redis:/var/lib/redis
    command: redis-server --requirepass password

  redis_exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    entrypoint: /bin/redis_exporter -redis.password 'password' -redis.addr redis://redis-server:6379


  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - redis-server:redis-server
      - redis_exporter:redis_exporter
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana-ui:
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - prometheus-server:prometheus